#!/bin/sh

BUILD_DIR=build
LINUX_PATH=..
MAC_ADDRESS=de:ad:be:ef:ca:fe

most_qemu_args="-kernel ${LINUX_PATH}/arch/x86_64/boot/bzImage -initrd ${BUILD_DIR}/initramfs.cpio.gz -no-reboot -nographic -device pci-testdev -netdev tap,id=mynet0 -device rtl8139,netdev=mynet0,mac=${MAC_ADDRESS}"

# Make sure we have sudo token
sudo id > /dev/null 2>/dev/null

exec_test ()
{
    sudo timeout 10 qemu-system-x86_64 ${most_qemu_args} -append "console=ttyS0 panic=-1 loglevel=15 init='/init tval_v2send'" &

    sleep 0.5  # It's annoying to find a better way
    sudo ip a add dev tap0 192.168.252.2/24

    timeout 10 nc -lnvu -p 9999 | grep "tvalv2|send" && echo "OK - tvalv2 send" || echo "NOK - tvalv2 send"
    wait
}

exec_test
