name: C/C++ CI

# Became obsolete in favor of c-tests.yml, only enable manual run
on:
  workflow_dispatch:
  # pull_request:
  #   paths:
  #     - 'drivers/**/*.[ch]'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test code formatting
      run: make -C pfa test_format
