name: C tests

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install musl-gcc
      run: apt install musl musl-tools
    - name: Test code formatting
      run: make -C pfa test_format
    - name: Validation test of v0
      run: make -C pfa ctval_v0
