name: Rust tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'drivers/**/*.rs'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install musl-gcc
      run: sudo apt install musl musl-tools qemu-system libxml2 libelf-dev bc libssl-dev
    - name: Test code formatting
      run: make -C pfa rust_testformat
    - name: Validation test of v0
      run: make -C pfa rtval_v0
    - name: Validation test of v1
      run: make -C pfa rtval_v1
